name: ChestShop
main: muqsit\chestshop\ChestShop
api: [3.0.0, 4.0.0]
version: 4
author:
- Muqsit
- tim03we
commands:
  servers:
    aliases: ["selector", "server", "transfer"]
permissions:
  chestshop.command.opcmd:
    default: op

